### PR TITLE
inventory:itemnotify convar to disable NUI Item update notification

### PR DESCRIPTION
**Pull request by ESK0**

### CODE REVIEW

**Comment by thelindat** [comment]
This sounds horrible; why?

**Comment by ESK0** [comment]
> This sounds horrible; why?

I believe that many people like me prefer minimalism. It is also suitable for a lot of serious RP servers, where notifications of a similar type are non-wl shit

**Comment by thelindat** [comment]
> suitable for a lot of serious RP servers

In real life, when somebody hands me something or I pick something up, I don't need to look through my pockets and try to work out what I just got..

I do want a more minimalist style in the future, but removing them entirely is bizarre; yes I get it's an optional convar but 😕.

**Comment by ESK0** [comment]
It is entirely up to you, I believe that a lot of people like a similar style notification and that's why I left it on by default.

I also believe that everyone will notice, for example, that he is holding a gun or that when he reloads the gun, it is more than clear that the amount of bullets in the inventory has been reduced.

**Pull request merged**
