### PR TITLE
feat(shops): Fixed price option

### PR DESCRIPTION
**Pull request by antond15**
Useful for some items like weapons, tickets, ID card etc.

### CODE REVIEW

**Comment by thelindat** [comment]
I think I'd prefer removing random prices and calling it as a function for price instead.

**Comment by antond15** [comment]
> I think I'd prefer removing random prices and calling it as a function for price instead.

If I understood correctly - instead of setting fixed price, you want to set a random price per shop item and remove the config option for this?

**Comment by thelindat** [comment]
```lua
local function randomPrice(price, min, max)
    return math.ceil(price * (math.random(min, max)/100))
end
```

Something like this, then have to explicitly make it fluctuate.

**Comment by frazz1234** [comment]
Could be very amazing .. 

But if an item is more expensive like in a shop then  other one, it can make some trouble. Like a holder more cheaper in the black market than réguler shop 🤷‍♂️

**Comment by thelindat** [comment]
Will look into this at a future date - likely going to add more stuff for shops alongside the items API.

**Pull request closed without merging**
