### PR TITLE
feat: register external items

### PR DESCRIPTION
**Pull request by Andyyy7666**
1. Create a resource:
2. create `test.lua` and add this.
```lua
return {
	['testburger'] = {
		label = 'Test Burger',
		weight = 220,
		degrade = 60,
		client = {
			status = { hunger = 200000 },
			anim = 'eating',
			prop = 'burger',
			usetime = 2500,
			-- export = 'ox_inventory_examples.testburger'
		},
		server = {
			-- export = 'ox_inventory_examples.testburger',
			test = 'what an amazingly delicious burger, amirite?'
		},
		buttons = {
			{
				label = 'Lick it',
				action = function(slot)
					print('You licked the burger')
				end
			},
			{
				label = 'Squeeze it',
				action = function(slot)
					print('You squeezed the burger :(')
				end
			}
		},
		consume = 0.3
	},
}
```

3. add to `fxmanifest.lua`:
```lua
file "test.lua"
ox_inventory_items "test.lua"
```

Done, this is what the community has asked for. Doesn't have to be over complicated this is perfect, only thing is that the resource that has the items has to be started before ox inventory which means that if a resource has ox inventory as a dependecy can't use this. I personally don't usually have ox_inventory as a dependency but have other ways to check.

### CODE REVIEW

**Comment by Andyyy7666** [comment]
The check for the external resource to be started can be removed and then ox inventory can be a dependency because it will also read items from stopped resources.

**Comment by jag3dagster** [comment]
Local iteration on a resource isn't handled in this code. Say a developer was working on their resource and needed to iterate on an item for some reason, they would need to restart their resource and then restart ox_inventory. Not devistating, but definitely annoying.

**Comment by Andyyy7666** [comment]
Yes I agree, that wouldn't be a problem if this below wasn't the case.
> not as simple as just adding an export and requires rewriting large parts of the code and the UI to properly support it. - linden

It's annoying but `ox_inventory/data/items.lua` can be used for development. This is just useful for when releasing resources to the public.

**Comment by thelindat** [comment]
I don't want 3rd party files loaded as modules or into the inventory _ENV.

**Pull request closed without merging**
