### PR TITLE
feat(server): Command to open Inventorys of offline players

### PR DESCRIPTION
**Pull request by Justus-Braun**
Issue: #690

### CODE REVIEW

**Comment by thelindat** [comment]
I have some problems with how this is implemented, but the most glaring thing is that people want to be able to open, interact with, and manipulate (AddItem/RemoveItem) these inventories.

I can't store player inventory by anything but playerId because of compatibility (and that's far easier to use), but loading offline player inventories would need me to store by character identifier, i.e. ESX's char1:license, QB's cid, Ox's charid - the last one being a number that would conflict with playerId.

**Comment by Justus-Braun** [comment]
That's the problem I had. A solution would be to store player inventories as normal inventories, but it could break backwards compatibility.

**Comment by CeebDev** [comment]
> I have some problems with how this is implemented, but the most glaring thing is that people want to be able to open, interact with, and manipulate (AddItem/RemoveItem) these inventories.
> 
> I can't store player inventory by anything but playerId because of compatibility (and that's far easier to use), but loading offline player inventories would need me to store by character identifier, i.e. ESX's char1:license, QB's cid, Ox's charid - the last one being a number that would conflict with playerId.

Ox can retrieve player by stateId instead of charId ?

**Comment by thelindat** [comment]
> Ox can retrieve player by stateId instead of charId ?

> I can't store player inventory by anything but playerId because of compatibility

**Pull request closed without merging**
