### PR TITLE
full translate to czech

### PR DESCRIPTION
**Pull request by itIsMaku**
my PR to translate cfx lua scheduler was denied. idk why. i just wanna say that this PR must be approved, because cz_inventory is the best inventory system and czech republic is the most important country on the world
image

### CODE REVIEW

**Comment by totsu0jv** [comment]
czech_inventory is finally here... 😱

**Comment by badfantomasss** [comment]
Nice pr bro 😱

**Comment by Sk1y** [comment]
Nice PR omg, finally its here

**Comment by itIsMaku** [comment]
**Update:**
- Docs translated
- Logo edited
czinvlogo

**Pull request closed without merging**
