### PR TITLE
Add a one Key option

### PR DESCRIPTION
**Pull request by zf-development**
Add the option of using only one key (F2).

Add this to the documentation:

setr inventory:oneKey false
sert inventory:keys ['F2', 'K', 'Z']
# If you only want to have one to control all inventories.
setr inventory:oneKey true

The inventory:keys will still need the 3 keys if error is made in the configs by the users.

### CODE REVIEW

**Comment by thelindat** [comment]
With few logic changes you can get pretty much the same result by just binding to the same key; I really don't like a single-key implementation though.

**Comment by zf-development** [comment]
I tried to just put the same key and it actually doesn't work. Here's the reason why BUT I just got an idea and will change the code today. For something "easier" (no configuration required)

**Comment by thelindat** [comment]
> I tried to just put the same key and it actually doesn't work

That's why I said it would require some changes.

**Comment by zf-development** [comment]
This is currently being completly remake.

**Pull request closed without merging**
