### PR TITLE
items total weight

### PR DESCRIPTION
**Pull request by Frowmza**
total weight should be counted as total item count multiply item weight i guess?

### CODE REVIEW

**Comment by thelindat** [comment]
Unless something changed, slot != item.
Slot is the data for the slot, which _contains_ item data, but the slot weight is `(item.weight + item.metadata.weight) * item.count`.

I'm also not certain where this gets used since the server reports the inventory weight to the client anyway. Did you actually _see_ an issue or decide this was problematic when going through code?

**Comment by Frowmza** [comment]
then the totalWeight function should look like this 
```
const getTotalWeight = (items: Inventory['items']) =>
  items.reduce((totalWeight, slot) => (isSlotGotItem(slot) ? totalWeight + (slot.metadata?.weight ? (slot.weight + slot.metadata?.weight) * slot.amount : slot.weight * slot.amount) : totalWeight), 0);
```

**Comment by thelindat** [comment]
> then the totalWeight function should look like this
> 
> ```
> const getTotalWeight = (items: Inventory['items']) =>
>   items.reduce((totalWeight, slot) => (isSlotGotItem(slot) ? totalWeight + (slot.metadata?.weight ? (slot.weight + slot.metadata?.weight) * slot.amount : slot.weight * slot.amount) : totalWeight), 0);
> ```

You're not listening. The slot weight is set on the server and sent to the client, which gets sent into the ui.

**Comment by Frowmza** [comment]
and in stackitems you only get 1 item weight cause they have same weight and items with metadata wight cannot be stacked

```
targetInventory.items[toSlot.slot - 1] = {
        ...targetInventory.items[toSlot.slot - 1],
        amount: toSlot.amount + amount,
        weight: fromSlot.weight,
    };
 ```

**Pull request closed without merging**
