### PR TITLE
add set datadog:hostname to default cfg

### PR DESCRIPTION
**Pull request by N-fire**
documentation change for my pull request : https://github.com/overextended/ox_inventory/pull/555

### CODE REVIEW

**Comment by duckysuck** [comment]
that link doesnt go anywhere @N-fire

**Comment by LukeWasTakenn** [comment]
Why do you have 2 PRs on this?

**Comment by N-fire** [comment]
Because one is for the main branch and that he other one is for the documentation 
I don't know if it's possible to make one pr for multiple multiple branch.

**Comment by LukeWasTakenn** [comment]
Oh I didn't even notice the other one was to the docs, yeah that's fine.

**Pull request merged**
