### PR TITLE
Almost 100% Hungarian translate

### PR DESCRIPTION
**Pull request by Rav3n95**

### CODE REVIEW

**Comment by dunak-debug** [comment]
Almost 100%?

**Comment by Rav3n95** [comment]
> 

Few lines are missing, also Hungarian language are really complicated compare to English. Propably will have to correct few words here and there.

**Comment by dunak-debug** [comment]
> Few lines are missing, also Hungarian language are really complicated compare to English. Propably will have to correct few words here and there.

Alright just make it draft until it’s done

**Comment by thelindat** [comment]
@Rav3n95 is this ready?

**Pull request closed without merging**
