### PR TITLE
Limit the quantity for an item (Optional)

### PR DESCRIPTION
**Pull request by dolutattoo**
I think that's a must have to be able to prevent a player to carry more than X quantity of an item, even if the weight capacity is ok.
It's probably not the best way to do it at all, I'm a complete beginner, but at least you get the idea.

For example, you don't want to see a player with 15 heist bags in his inventory.
Or if you want to physically attach a chicken to the hand of a player when he just catched one from the farm.

PS: This was tested in `shops`, `trunks`, `gloveboxes`, and `give` feature with 3 players on the server. No issue for us, except when you `/steal` someone, didnt found where to put the limit (because of time, I work f*ing slowly ^^)

### CODE REVIEW

**Comment by thelindat** [comment]
While I don't see the point of limit in many cases, I'd rather see it implemented well rather than hacky methods (and not have to do it myself). Complete the requested changes before I test and do my own cleanup.

**Review by thelindat — CHANGES_REQUESTED** [review]

**Comment by dolutattoo** [comment]
I cannot use GetItemSlots inside modules files

**Comment by thelindat** [comment]
> I cannot use GetItemSlots in modules/*.lua
> 
> It require to edit: `local GetItemSlots = function(inv, item, metadata)` by this: `M.GetItemSlots = function(inv, item, metadata)`

Yes, that's fine.

**Comment by dolutattoo** [comment]
All requested changes are done

**Pull request merged**
