### PR TITLE
tweak(modules/inventory/server.lua): modify AddItem

### PR DESCRIPTION
**Pull request by mahanmoulaei**
Now the correct amount of unique(not stack) items would be added to the inventory.

### CODE REVIEW

**Comment by thelindat** [comment]
Lazy to review and test rn; this is to add multiple items to different slots when an item is unique, rather than forcing a count of 1?
Items.Metadata would need to be called for each slot to ensure each item gets unique metadata; that function also forcibly sets a count of 1 in some cases.

**Comment by mahanmoulaei** [comment]
>this is to add multiple items to different slots when an item is unique, rather than forcing a count of 1? 

Yes

----
> Items.Metadata would need to be called for each slot to ensure each item gets unique metadata

Ok I'll change the code

----
> that function also forcibly sets a count of 1 in some cases

Yes I'm aware of this and the way I looked at it, shouldn't be conflicting with my PR(hopefully)

**Comment by thelindat** [comment]
I have a few issues with how this is done, and it's easier to update the functionality myself than talk through the changes I'd like to see.

**Comment by mahanmoulaei** [comment]
> I have a few issues with how this is done, and it's easier to update the functionality myself than talk through the changes I'd like to see.

Sure Linden, do as you wish.

**Comment by thelindat** [comment]
@mahanmoulaei https://github.com/overextended/ox_inventory/commit/7de222bdc27e978961c18faf8eb6b3f17e74ccdd

**Comment by mahanmoulaei** [comment]
> @mahanmoulaei [7de222b](https://github.com/overextended/ox_inventory/commit/7de222bdc27e978961c18faf8eb6b3f17e74ccdd)

Perfect Thank you!!!

**Pull request closed without merging**
